// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Spark.Data;

#nullable disable

namespace Spark.Data.Migrations
{
    [DbContext(typeof(SparkDBContext))]
    [Migration("20230525152046_InitMigration")]
    partial class InitMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("Spark.Data.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("PostId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            PostId = 1,
                            AuthorId = "user_2QI1HUBJlRNcyGJNHON6JBBm4O7",
                            Content = "1⚡",
                            CreatedAt = new DateTime(2023, 5, 25, 16, 20, 46, 222, DateTimeKind.Local).AddTicks(972)
                        },
                        new
                        {
                            PostId = 2,
                            AuthorId = "user_2QI1HUBJlRNcyGJNHON6JBBm4O7",
                            Content = "2⚡",
                            CreatedAt = new DateTime(2023, 5, 25, 16, 20, 46, 222, DateTimeKind.Local).AddTicks(1068)
                        },
                        new
                        {
                            PostId = 3,
                            AuthorId = "user_2QI1HUBJlRNcyGJNHON6JBBm4O7",
                            Content = "3⚡",
                            CreatedAt = new DateTime(2023, 5, 25, 16, 20, 46, 222, DateTimeKind.Local).AddTicks(1071)
                        },
                        new
                        {
                            PostId = 4,
                            AuthorId = "user_2QI1HUBJlRNcyGJNHON6JBBm4O7",
                            Content = "4⚡",
                            CreatedAt = new DateTime(2023, 5, 25, 16, 20, 46, 222, DateTimeKind.Local).AddTicks(1074)
                        },
                        new
                        {
                            PostId = 5,
                            AuthorId = "user_2QI1HUBJlRNcyGJNHON6JBBm4O7",
                            Content = "5⚡",
                            CreatedAt = new DateTime(2023, 5, 25, 16, 20, 46, 222, DateTimeKind.Local).AddTicks(1076)
                        },
                        new
                        {
                            PostId = 6,
                            AuthorId = "user_2QI1HUBJlRNcyGJNHON6JBBm4O7",
                            Content = "6⚡",
                            CreatedAt = new DateTime(2023, 5, 25, 16, 20, 46, 222, DateTimeKind.Local).AddTicks(1078)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
