// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Spark.Data;

#nullable disable

namespace Spark.Data.Migrations
{
    [DbContext(typeof(SparkDBContext))]
    partial class SparkDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("Spark.Data.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("PostId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            PostId = 1,
                            AuthorId = 25,
                            Content = "1⚡",
                            CreatedAt = new DateTime(2023, 5, 25, 10, 1, 54, 182, DateTimeKind.Local).AddTicks(1923)
                        },
                        new
                        {
                            PostId = 2,
                            AuthorId = 40,
                            Content = "2⚡",
                            CreatedAt = new DateTime(2023, 5, 25, 10, 1, 54, 182, DateTimeKind.Local).AddTicks(2043)
                        },
                        new
                        {
                            PostId = 3,
                            AuthorId = 84,
                            Content = "3⚡",
                            CreatedAt = new DateTime(2023, 5, 25, 10, 1, 54, 182, DateTimeKind.Local).AddTicks(2048)
                        },
                        new
                        {
                            PostId = 4,
                            AuthorId = 46,
                            Content = "4⚡",
                            CreatedAt = new DateTime(2023, 5, 25, 10, 1, 54, 182, DateTimeKind.Local).AddTicks(2051)
                        },
                        new
                        {
                            PostId = 5,
                            AuthorId = 56,
                            Content = "5⚡",
                            CreatedAt = new DateTime(2023, 5, 25, 10, 1, 54, 182, DateTimeKind.Local).AddTicks(2061)
                        },
                        new
                        {
                            PostId = 6,
                            AuthorId = 68,
                            Content = "6⚡",
                            CreatedAt = new DateTime(2023, 5, 25, 10, 1, 54, 182, DateTimeKind.Local).AddTicks(2064)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
